<!DOCTYPE html>
<html>
	<head>
		<title>accenture hpit</title>
		<!--meta name="viewport" content="width=device-width, initial-scale=1.0"-->
		<meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1.0, maximum-scale=1, user-scalable=yes" />
		<!-- Bootstrap -->
		<link href="css/bootstrap.min.css" rel="stylesheet" media="screen">
        <!--link href="css/reset.css" rel="stylesheet" media="screen"-->
		<link href="css/hpit.css" rel="stylesheet" media="screen">

		<!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
		<!--[if lt IE 9]>
			<script src="../../assets/js/html5shiv.js"></script>
			<script src="../../assets/js/respond.min.js"></script>
		<![endif]-->
	</head>
	<body>

	<div id="ll-overlay">
		<div class="inner">
			<a class="closeVid" href="#">X</a>
			<div id="ll-player"></div>
		</div>
	</div>

<!-- Fixed navbar -->
    <div class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#"><img src="images/logo.png" width="128" height="36" /></a>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
            <li class="contact"><a href="#"><span class="icn"></span>contact</a></li>
            <li class="share">
            	<a href="#"><span class="icn"></span>share</a>
            	<div class="social">
            		<a href="https://plus.google.com/share?url=http://accenture-hpit.herokuapp.com/index.php" target="_blank" class="google"></a>
            		<a href="http://www.facebook.com/share.php?u=http://accenture-hpit.herokuapp.com/index.php" target="_blank" class="facebook"></a>
            		<a href="http://twitter.com/share?url=http://accenture-hpit.herokuapp.com/index.php" target="_blank" class="twitter"></a>
                    <a href="http://www.linkedin.com/shareArticle?mini=true&url=http://accenture-hpit.herokuapp.com/index.php" target="_blank" class="linkedin"></a>
            		<!-- &title=http://bit.ly/adaptxt-beta-android&summary=http://bit.ly/adaptxt-beta-android&source=http://bit.ly/adaptxt-beta-android -->
            	</div>
            </li>
            <li class="download"><a href="#"><span class="icn"></span>get the study</a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>

    <div class="container main">
    	<div id="controls">
    		<!--<img src="images/menu-controls.png" width="77" height="181" />-->
    		<a href="#" class="arrows prev"></a>
    		<a href="#" class="txt" id="toggleMenu">Menu</a>
    		<a href="#" class="arrows nxt"></a>
    	</div>
    	<div id="sideMenu">
    		<ul>
    			<li><a href="#top" class="btt"><em>Back To Top</em></a></li>
    			<li data-insight-nav="1"><a href="#your-new-boss-your-customer"><span>01</span> <span>Your new boss? Your customer.</span></a></li>
    			<li data-insight-nav="2"><a href="#technology-is-inseparable-from-business-strategy"><span>02</span> <span>Technology is inseparable from business strategy</span></a></li>
    			<li data-insight-nav="3"><a href="#context-is-king"><span>03</span> <span>Context is king.</span></a></li>
    			<li data-insight-nav="4"><a href="#flexibility-first"><span>04</span> <span>Flexibility first.</span></a></li>
    			<li data-insight-nav="5"><a href="#be-fearlessly-digital"><span>05</span> <span>Be fearlessly digital.</span></a></li>
    			<li data-insight-nav="6"><a href="#survival-of-the-quickest"><span>06</span> <span>Survival of the quickest</span></a></li>
    			<li data-insight-nav="7"><a href="#all-data-is-not-created-equal"><span>07</span> <span>All data is not created equal.</span></a></li>
    			<li data-insight-nav="8"><a href="#power-to-the-people"><span>08</span> <span>Power to the people.</span></a></li>
    			<li data-insight-nav="9"><a href="#build-your-capabilities-around-talent-not-technology"><span>09</span> <span>Build your capabilities around talent, not technology.</span></a></li>
    			<li data-insight-nav="10"><a href="#take-a-holistic-stance-on-security-and-risk"><span>10</span> <span>Take a holistic stance on security and risk</span></a></li>
    		</ul>
    		<a href="#" class="closeX">&nbsp;</a>
    	</div>
    	<div class="hero" id="hero">
            <video width="auto" height="100%" autoplay loop>
                <source src="images/blue-loop.mp4" type="video/mp4">
                <source src="images/blue-loop.ogg" type="video/ogg">
                Your browser does not support the video tag.
            </video>
            <div>
                <h3>Accenture High Performance IT Survey 2013</h3>
                <h1>The Rise of the Strategy Savvy CIO</h1>
                <p>IT now means "in transition" as CIOs move from the server room to the board room and help set the strategic digital agenda. <strong>Accenture CTO Paul Daugherty</strong> shares his point of view on this year's key insights.</p>
                <a href="#" class="playVid"></a>
            </div>
        </div>
        <div id="accMark"><img src="images/accenture-mark.png" width="532" height="536" /></div>
        <div class="whiteAngle">whiteAngle</div>
    	<div class="bgImages" id="bgImages">
    		<div class="bgImg" data-insight="10"><img src="images/bg-japanese.jpg" /></div>
    		<div class="bgImg" data-insight="9"><img src="images/bg-beach.jpg" /></div>
    		<div class="bgImg" data-insight="8"><img src="images/bg-sea.jpg" /></div>
    		<div class="bgImg" data-insight="7"><img src="images/bg-sunflower.jpg" /></div>
    		<div class="bgImg" data-insight="6"><img src="images/bg-lake.jpg" /></div>
    		<div class="bgImg" data-insight="5"><img src="images/bg-field.jpg" /></div>
    		<div class="bgImg" data-insight="4"><img src="images/bg-edinburgh.jpg" /></div>
    		<div class="bgImg" data-insight="3"><img src="images/bg-boat.jpg" /></div>
    		<div class="bgImg" data-insight="2"><img src="images/bg-ocean.jpg" /></div>
    		<div class="bgImg" data-insight="1"><img src="images/bg-bridge.jpg" /></div>
    	</div>
    	<div class="insight" id="your-new-boss-your-customer" data-insight="1">
    		<div class="marker">
    			<div><span>01</span></div>
    		</div>
            <div class="insightTitle">
                <h6>CIO Action Item #1</h6>
                <h3>Your new boss? Your customer.</h3>
                <div class="social">
                    <a href="https://plus.google.com/share?url=http://accenture-hpit.herokuapp.com/index.php" target="_blank" class="google"></a>
                    <a href="http://www.facebook.com/share.php?u=http://accenture-hpit.herokuapp.com/index.php" target="_blank" class="facebook"></a>
                    <a href="http://twitter.com/share?url=http://accenture-hpit.herokuapp.com/index.php" target="_blank" class="twitter"></a>
                    <a href="http://www.linkedin.com/shareArticle?mini=true&url=http://accenture-hpit.herokuapp.com/index.php" target="_blank" class="linkedin"></a>
                </div>
            </div>
    		<div class="container content">
    			<div class="row">
                    <!--div class="left-col">lorem ipsum...</div-->
                    <div class="right-col col-xs-12 col-sm-6 col-md-6 col-lg-6 col-sm-offset-6 col-md-offset-6 col-lg-offset-6">
                        <p class="heading">
                        <span>Strategy straight talk:</span>
                        <span>“You can’t think like a database. You have to think like a customer.”</span>
                        </p>
                        <p>
                        <span>Why it’s important:</span>
                        <span>High performers have moved beyond internally focused objectives like cost and productivity. The new bulls-eye is the customer experience. </span>
                        </p>
                        <p>
                        <span>What you should know: (infographic)</span>
                        <span>High performers’ top 3 business objectives all point to improving the customer experience.</span>
                        </p>
                        <p>
                        <span>High performers</span>
                        <span>1.  Providing the right information to the right person at the right time</span>
                        <span>2.  Finding better ways to interact with customers</span>
                        <span>3.  Delivering new services or products to customers</span>
                        </p>
                        <p>
                        <span>Others</span>
                        <span>1.  Cutting business operational costs</span>
                        <span>2.  Increasing workforce productivity</span>
                        <span>3.  Automating core business processes</span>
                        </p>
                        <p>
                        <span>High performers are also…</span>
                        <span>   Getting social. Social channels open up collaboration and create personal dialogue with key customers.</span>
                        <span>   Building relationships. Both acquisition and sales get a boost by giving potential customers what they want, and listening to what current customers have to say.</span>
                        </p>
                        <p>lorem...</p>
                    </div>
                </div>
			</div>
    	</div>
    	<div class="insight" id="technology-is-inseparable-from-business-strategy" data-insight="2">
    		<!--div class="bgImg"><img src="images/bg_lake.jpg" /></div-->
    		<div class="marker">
    			<div><span>02</span></div>
    		</div>
            <div class="insightTitle">
                <h6>CIO Action Item #2</h6>
                <h3>Technology is inseparable from business strategy.</h3>
                <div class="social">
                    <a href="https://plus.google.com/share?url=http://accenture-hpit.herokuapp.com/index.php" target="_blank" class="google"></a>
                    <a href="http://www.facebook.com/share.php?u=http://accenture-hpit.herokuapp.com/index.php" target="_blank" class="facebook"></a>
                    <a href="http://twitter.com/share?url=http://accenture-hpit.herokuapp.com/index.php" target="_blank" class="twitter"></a>
                    <a href="http://www.linkedin.com/shareArticle?mini=true&url=http://accenture-hpit.herokuapp.com/index.php" target="_blank" class="linkedin"></a>
                </div>
            </div>
    		<div class="container content">
                <div class="row">
                    <!--div class="left-col">lorem ipsum...</div-->
                    <div class="right-col col-xs-12 col-sm-6 col-md-6 col-lg-6 col-sm-offset-6 col-md-offset-6 col-lg-offset-6">
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis posuere risus nibh, quis lobortis lectus aliquet vitae. Nullam porttitor nisl sit amet est lacinia auctor. In eleifend quis ipsum sed suscipit. Vivamus mollis ornare ipsum fermentum luctus. Proin dapibus viverra libero in ultrices. Donec sed felis eleifend, varius neque accumsan, varius quam. Ut eleifend nisi quis velit aliquam, non porta nunc placerat. Sed sed quam lectus. Donec malesuada neque arcu, nec vestibulum magna pharetra nec. Cras sit amet viverra neque, vitae laoreet tellus. Sed ultrices ante eget arcu tincidunt tincidunt. Curabitur rutrum a elit a consequat. Aenean sed dui vitae sapien ornare lacinia. Donec nec rhoncus sem. Vivamus egestas lacinia orci eu elementum. Curabitur pharetra vulputate augue, sit amet gravida arcu posuere eu.</p>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis posuere risus nibh, quis lobortis lectus aliquet vitae. Nullam porttitor nisl sit amet est lacinia auctor. In eleifend quis ipsum sed suscipit. Vivamus mollis ornare ipsum fermentum luctus. Proin dapibus viverra libero in ultrices. Donec sed felis eleifend, varius neque accumsan, varius quam. Ut eleifend nisi quis velit aliquam, non porta nunc placerat. Sed sed quam lectus. Donec malesuada neque arcu, nec vestibulum magna pharetra nec. Cras sit amet viverra neque, vitae laoreet tellus. Sed ultrices ante eget arcu tincidunt tincidunt. Curabitur rutrum a elit a consequat. Aenean sed dui vitae sapien ornare lacinia. Donec nec rhoncus sem. Vivamus egestas lacinia orci eu elementum. Curabitur pharetra vulputate augue, sit amet gravida arcu posuere eu.</p>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis posuere risus nibh, quis lobortis lectus aliquet vitae. Nullam porttitor nisl sit amet est lacinia auctor. In eleifend quis ipsum sed suscipit. Vivamus mollis ornare ipsum fermentum luctus. Proin dapibus viverra libero in ultrices. Donec sed felis eleifend, varius neque accumsan, varius quam. Ut eleifend nisi quis velit aliquam, non porta nunc placerat. Sed sed quam lectus. Donec malesuada neque arcu, nec vestibulum magna pharetra nec. Cras sit amet viverra neque, vitae laoreet tellus. Sed ultrices ante eget arcu tincidunt tincidunt. Curabitur rutrum a elit a consequat. Aenean sed dui vitae sapien ornare lacinia. Donec nec rhoncus sem. Vivamus egestas lacinia orci eu elementum. Curabitur pharetra vulputate augue, sit amet gravida arcu posuere eu.</p>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis posuere risus nibh, quis lobortis lectus aliquet vitae. Nullam porttitor nisl sit amet est lacinia auctor. In eleifend quis ipsum sed suscipit. Vivamus mollis ornare ipsum fermentum luctus. Proin dapibus viverra libero in ultrices. Donec sed felis eleifend, varius neque accumsan, varius quam. Ut eleifend nisi quis velit aliquam, non porta nunc placerat. Sed sed quam lectus. Donec malesuada neque arcu, nec vestibulum magna pharetra nec. Cras sit amet viverra neque, vitae laoreet tellus. Sed ultrices ante eget arcu tincidunt tincidunt. Curabitur rutrum a elit a consequat. Aenean sed dui vitae sapien ornare lacinia. Donec nec rhoncus sem. Vivamus egestas lacinia orci eu elementum. Curabitur pharetra vulputate augue, sit amet gravida arcu posuere eu.</p>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis posuere risus nibh, quis lobortis lectus aliquet vitae. Nullam porttitor nisl sit amet est lacinia auctor. In eleifend quis ipsum sed suscipit. Vivamus mollis ornare ipsum fermentum luctus. Proin dapibus viverra libero in ultrices. Donec sed felis eleifend, varius neque accumsan, varius quam. Ut eleifend nisi quis velit aliquam, non porta nunc placerat. Sed sed quam lectus. Donec malesuada neque arcu, nec vestibulum magna pharetra nec. Cras sit amet viverra neque, vitae laoreet tellus. Sed ultrices ante eget arcu tincidunt tincidunt. Curabitur rutrum a elit a consequat. Aenean sed dui vitae sapien ornare lacinia. Donec nec rhoncus sem. Vivamus egestas lacinia orci eu elementum. Curabitur pharetra vulputate augue, sit amet gravida arcu posuere eu.</p>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis posuere risus nibh, quis lobortis lectus aliquet vitae. Nullam porttitor nisl sit amet est lacinia auctor. In eleifend quis ipsum sed suscipit. Vivamus mollis ornare ipsum fermentum luctus. Proin dapibus viverra libero in ultrices. Donec sed felis eleifend, varius neque accumsan, varius quam. Ut eleifend nisi quis velit aliquam, non porta nunc placerat. Sed sed quam lectus. Donec malesuada neque arcu, nec vestibulum magna pharetra nec. Cras sit amet viverra neque, vitae laoreet tellus. Sed ultrices ante eget arcu tincidunt tincidunt. Curabitur rutrum a elit a consequat. Aenean sed dui vitae sapien ornare lacinia. Donec nec rhoncus sem. Vivamus egestas lacinia orci eu elementum. Curabitur pharetra vulputate augue, sit amet gravida arcu posuere eu.</p>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis posuere risus nibh, quis lobortis lectus aliquet vitae. Nullam porttitor nisl sit amet est lacinia auctor. In eleifend quis ipsum sed suscipit. Vivamus mollis ornare ipsum fermentum luctus. Proin dapibus viverra libero in ultrices. Donec sed felis eleifend, varius neque accumsan, varius quam. Ut eleifend nisi quis velit aliquam, non porta nunc placerat. Sed sed quam lectus. Donec malesuada neque arcu, nec vestibulum magna pharetra nec. Cras sit amet viverra neque, vitae laoreet tellus. Sed ultrices ante eget arcu tincidunt tincidunt. Curabitur rutrum a elit a consequat. Aenean sed dui vitae sapien ornare lacinia. Donec nec rhoncus sem. Vivamus egestas lacinia orci eu elementum. Curabitur pharetra vulputate augue, sit amet gravida arcu posuere eu.</p>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis posuere risus nibh, quis lobortis lectus aliquet vitae. Nullam porttitor nisl sit amet est lacinia auctor. In eleifend quis ipsum sed suscipit. Vivamus mollis ornare ipsum fermentum luctus. Proin dapibus viverra libero in ultrices. Donec sed felis eleifend, varius neque accumsan, varius quam. Ut eleifend nisi quis velit aliquam, non porta nunc placerat. Sed sed quam lectus. Donec malesuada neque arcu, nec vestibulum magna pharetra nec. Cras sit amet viverra neque, vitae laoreet tellus. Sed ultrices ante eget arcu tincidunt tincidunt. Curabitur rutrum a elit a consequat. Aenean sed dui vitae sapien ornare lacinia. Donec nec rhoncus sem. Vivamus egestas lacinia orci eu elementum. Curabitur pharetra vulputate augue, sit amet gravida arcu posuere eu.</p>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis posuere risus nibh, quis lobortis lectus aliquet vitae. Nullam porttitor nisl sit amet est lacinia auctor. In eleifend quis ipsum sed suscipit. Vivamus mollis ornare ipsum fermentum luctus. Proin dapibus viverra libero in ultrices. Donec sed felis eleifend, varius neque accumsan, varius quam. Ut eleifend nisi quis velit aliquam, non porta nunc placerat. Sed sed quam lectus. Donec malesuada neque arcu, nec vestibulum magna pharetra nec. Cras sit amet viverra neque, vitae laoreet tellus. Sed ultrices ante eget arcu tincidunt tincidunt. Curabitur rutrum a elit a consequat. Aenean sed dui vitae sapien ornare lacinia. Donec nec rhoncus sem. Vivamus egestas lacinia orci eu elementum. Curabitur pharetra vulputate augue, sit amet gravida arcu posuere eu.</p>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis posuere risus nibh, quis lobortis lectus aliquet vitae. Nullam porttitor nisl sit amet est lacinia auctor. In eleifend quis ipsum sed suscipit. Vivamus mollis ornare ipsum fermentum luctus. Proin dapibus viverra libero in ultrices. Donec sed felis eleifend, varius neque accumsan, varius quam. Ut eleifend nisi quis velit aliquam, non porta nunc placerat. Sed sed quam lectus. Donec malesuada neque arcu, nec vestibulum magna pharetra nec. Cras sit amet viverra neque, vitae laoreet tellus. Sed ultrices ante eget arcu tincidunt tincidunt. Curabitur rutrum a elit a consequat. Aenean sed dui vitae sapien ornare lacinia. Donec nec rhoncus sem. Vivamus egestas lacinia orci eu elementum. Curabitur pharetra vulputate augue, sit amet gravida arcu posuere eu.</p>
                    </div>
                </div>
            </div>
    	</div>
    	<div class="insight" id="context-is-king" data-insight="3">
    		<div class="marker">
    			<div><span>03</span></div>
    		</div>
            <div class="insightTitle">
                <h6>CIO Action Item #3</h6>
                <h3>Context is king.</h3>
                <div class="social">
                    <a href="https://plus.google.com/share?url=http://accenture-hpit.herokuapp.com/index.php" target="_blank" class="google"></a>
                    <a href="http://www.facebook.com/share.php?u=http://accenture-hpit.herokuapp.com/index.php" target="_blank" class="facebook"></a>
                    <a href="http://twitter.com/share?url=http://accenture-hpit.herokuapp.com/index.php" target="_blank" class="twitter"></a>
                    <a href="http://www.linkedin.com/shareArticle?mini=true&url=http://accenture-hpit.herokuapp.com/index.php" target="_blank" class="linkedin"></a>
                </div>
            </div>
    		<div class="container content">
                <div class="row">
                    <!--div class="left-col">lorem ipsum...</div-->
                    <div class="right-col col-xs-12 col-sm-6 col-md-6 col-lg-6 col-sm-offset-6 col-md-offset-6 col-lg-offset-6">
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis posuere risus nibh, quis lobortis lectus aliquet vitae. Nullam porttitor nisl sit amet est lacinia auctor. In eleifend quis ipsum sed suscipit. Vivamus mollis ornare ipsum fermentum luctus. Proin dapibus viverra libero in ultrices. Donec sed felis eleifend, varius neque accumsan, varius quam. Ut eleifend nisi quis velit aliquam, non porta nunc placerat. Sed sed quam lectus. Donec malesuada neque arcu, nec vestibulum magna pharetra nec. Cras sit amet viverra neque, vitae laoreet tellus. Sed ultrices ante eget arcu tincidunt tincidunt. Curabitur rutrum a elit a consequat. Aenean sed dui vitae sapien ornare lacinia. Donec nec rhoncus sem. Vivamus egestas lacinia orci eu elementum. Curabitur pharetra vulputate augue, sit amet gravida arcu posuere eu.</p>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis posuere risus nibh, quis lobortis lectus aliquet vitae. Nullam porttitor nisl sit amet est lacinia auctor. In eleifend quis ipsum sed suscipit. Vivamus mollis ornare ipsum fermentum luctus. Proin dapibus viverra libero in ultrices. Donec sed felis eleifend, varius neque accumsan, varius quam. Ut eleifend nisi quis velit aliquam, non porta nunc placerat. Sed sed quam lectus. Donec malesuada neque arcu, nec vestibulum magna pharetra nec. Cras sit amet viverra neque, vitae laoreet tellus. Sed ultrices ante eget arcu tincidunt tincidunt. Curabitur rutrum a elit a consequat. Aenean sed dui vitae sapien ornare lacinia. Donec nec rhoncus sem. Vivamus egestas lacinia orci eu elementum. Curabitur pharetra vulputate augue, sit amet gravida arcu posuere eu.</p>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis posuere risus nibh, quis lobortis lectus aliquet vitae. Nullam porttitor nisl sit amet est lacinia auctor. In eleifend quis ipsum sed suscipit. Vivamus mollis ornare ipsum fermentum luctus. Proin dapibus viverra libero in ultrices. Donec sed felis eleifend, varius neque accumsan, varius quam. Ut eleifend nisi quis velit aliquam, non porta nunc placerat. Sed sed quam lectus. Donec malesuada neque arcu, nec vestibulum magna pharetra nec. Cras sit amet viverra neque, vitae laoreet tellus. Sed ultrices ante eget arcu tincidunt tincidunt. Curabitur rutrum a elit a consequat. Aenean sed dui vitae sapien ornare lacinia. Donec nec rhoncus sem. Vivamus egestas lacinia orci eu elementum. Curabitur pharetra vulputate augue, sit amet gravida arcu posuere eu.</p>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis posuere risus nibh, quis lobortis lectus aliquet vitae. Nullam porttitor nisl sit amet est lacinia auctor. In eleifend quis ipsum sed suscipit. Vivamus mollis ornare ipsum fermentum luctus. Proin dapibus viverra libero in ultrices. Donec sed felis eleifend, varius neque accumsan, varius quam. Ut eleifend nisi quis velit aliquam, non porta nunc placerat. Sed sed quam lectus. Donec malesuada neque arcu, nec vestibulum magna pharetra nec. Cras sit amet viverra neque, vitae laoreet tellus. Sed ultrices ante eget arcu tincidunt tincidunt. Curabitur rutrum a elit a consequat. Aenean sed dui vitae sapien ornare lacinia. Donec nec rhoncus sem. Vivamus egestas lacinia orci eu elementum. Curabitur pharetra vulputate augue, sit amet gravida arcu posuere eu.</p>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis posuere risus nibh, quis lobortis lectus aliquet vitae. Nullam porttitor nisl sit amet est lacinia auctor. In eleifend quis ipsum sed suscipit. Vivamus mollis ornare ipsum fermentum luctus. Proin dapibus viverra libero in ultrices. Donec sed felis eleifend, varius neque accumsan, varius quam. Ut eleifend nisi quis velit aliquam, non porta nunc placerat. Sed sed quam lectus. Donec malesuada neque arcu, nec vestibulum magna pharetra nec. Cras sit amet viverra neque, vitae laoreet tellus. Sed ultrices ante eget arcu tincidunt tincidunt. Curabitur rutrum a elit a consequat. Aenean sed dui vitae sapien ornare lacinia. Donec nec rhoncus sem. Vivamus egestas lacinia orci eu elementum. Curabitur pharetra vulputate augue, sit amet gravida arcu posuere eu.</p>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis posuere risus nibh, quis lobortis lectus aliquet vitae. Nullam porttitor nisl sit amet est lacinia auctor. In eleifend quis ipsum sed suscipit. Vivamus mollis ornare ipsum fermentum luctus. Proin dapibus viverra libero in ultrices. Donec sed felis eleifend, varius neque accumsan, varius quam. Ut eleifend nisi quis velit aliquam, non porta nunc placerat. Sed sed quam lectus. Donec malesuada neque arcu, nec vestibulum magna pharetra nec. Cras sit amet viverra neque, vitae laoreet tellus. Sed ultrices ante eget arcu tincidunt tincidunt. Curabitur rutrum a elit a consequat. Aenean sed dui vitae sapien ornare lacinia. Donec nec rhoncus sem. Vivamus egestas lacinia orci eu elementum. Curabitur pharetra vulputate augue, sit amet gravida arcu posuere eu.</p>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis posuere risus nibh, quis lobortis lectus aliquet vitae. Nullam porttitor nisl sit amet est lacinia auctor. In eleifend quis ipsum sed suscipit. Vivamus mollis ornare ipsum fermentum luctus. Proin dapibus viverra libero in ultrices. Donec sed felis eleifend, varius neque accumsan, varius quam. Ut eleifend nisi quis velit aliquam, non porta nunc placerat. Sed sed quam lectus. Donec malesuada neque arcu, nec vestibulum magna pharetra nec. Cras sit amet viverra neque, vitae laoreet tellus. Sed ultrices ante eget arcu tincidunt tincidunt. Curabitur rutrum a elit a consequat. Aenean sed dui vitae sapien ornare lacinia. Donec nec rhoncus sem. Vivamus egestas lacinia orci eu elementum. Curabitur pharetra vulputate augue, sit amet gravida arcu posuere eu.</p>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis posuere risus nibh, quis lobortis lectus aliquet vitae. Nullam porttitor nisl sit amet est lacinia auctor. In eleifend quis ipsum sed suscipit. Vivamus mollis ornare ipsum fermentum luctus. Proin dapibus viverra libero in ultrices. Donec sed felis eleifend, varius neque accumsan, varius quam. Ut eleifend nisi quis velit aliquam, non porta nunc placerat. Sed sed quam lectus. Donec malesuada neque arcu, nec vestibulum magna pharetra nec. Cras sit amet viverra neque, vitae laoreet tellus. Sed ultrices ante eget arcu tincidunt tincidunt. Curabitur rutrum a elit a consequat. Aenean sed dui vitae sapien ornare lacinia. Donec nec rhoncus sem. Vivamus egestas lacinia orci eu elementum. Curabitur pharetra vulputate augue, sit amet gravida arcu posuere eu.</p>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis posuere risus nibh, quis lobortis lectus aliquet vitae. Nullam porttitor nisl sit amet est lacinia auctor. In eleifend quis ipsum sed suscipit. Vivamus mollis ornare ipsum fermentum luctus. Proin dapibus viverra libero in ultrices. Donec sed felis eleifend, varius neque accumsan, varius quam. Ut eleifend nisi quis velit aliquam, non porta nunc placerat. Sed sed quam lectus. Donec malesuada neque arcu, nec vestibulum magna pharetra nec. Cras sit amet viverra neque, vitae laoreet tellus. Sed ultrices ante eget arcu tincidunt tincidunt. Curabitur rutrum a elit a consequat. Aenean sed dui vitae sapien ornare lacinia. Donec nec rhoncus sem. Vivamus egestas lacinia orci eu elementum. Curabitur pharetra vulputate augue, sit amet gravida arcu posuere eu.</p>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis posuere risus nibh, quis lobortis lectus aliquet vitae. Nullam porttitor nisl sit amet est lacinia auctor. In eleifend quis ipsum sed suscipit. Vivamus mollis ornare ipsum fermentum luctus. Proin dapibus viverra libero in ultrices. Donec sed felis eleifend, varius neque accumsan, varius quam. Ut eleifend nisi quis velit aliquam, non porta nunc placerat. Sed sed quam lectus. Donec malesuada neque arcu, nec vestibulum magna pharetra nec. Cras sit amet viverra neque, vitae laoreet tellus. Sed ultrices ante eget arcu tincidunt tincidunt. Curabitur rutrum a elit a consequat. Aenean sed dui vitae sapien ornare lacinia. Donec nec rhoncus sem. Vivamus egestas lacinia orci eu elementum. Curabitur pharetra vulputate augue, sit amet gravida arcu posuere eu.</p>
                    </div>
                </div>
            </div>
    	</div>
    	<div class="insight" id="flexibility-first" data-insight="4">
    		<div class="marker">
    			<div><span>04</span></div>
    		</div>
            <div class="insightTitle">
                <h6>CIO Action Item #4</h6>
                <h3>Flexibility first.</h3>
                <div class="social">
                    <a href="https://plus.google.com/share?url=http://accenture-hpit.herokuapp.com/index.php" target="_blank" class="google"></a>
                    <a href="http://www.facebook.com/share.php?u=http://accenture-hpit.herokuapp.com/index.php" target="_blank" class="facebook"></a>
                    <a href="http://twitter.com/share?url=http://accenture-hpit.herokuapp.com/index.php" target="_blank" class="twitter"></a>
                    <a href="http://www.linkedin.com/shareArticle?mini=true&url=http://accenture-hpit.herokuapp.com/index.php" target="_blank" class="linkedin"></a>
                </div>
            </div>
    		<div class="container content">
                <div class="row">
                    <!--div class="left-col">lorem ipsum...</div-->
                    <div class="right-col col-xs-12 col-sm-6 col-md-6 col-lg-6 col-sm-offset-6 col-md-offset-6 col-lg-offset-6">
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis posuere risus nibh, quis lobortis lectus aliquet vitae. Nullam porttitor nisl sit amet est lacinia auctor. In eleifend quis ipsum sed suscipit. Vivamus mollis ornare ipsum fermentum luctus. Proin dapibus viverra libero in ultrices. Donec sed felis eleifend, varius neque accumsan, varius quam. Ut eleifend nisi quis velit aliquam, non porta nunc placerat. Sed sed quam lectus. Donec malesuada neque arcu, nec vestibulum magna pharetra nec. Cras sit amet viverra neque, vitae laoreet tellus. Sed ultrices ante eget arcu tincidunt tincidunt. Curabitur rutrum a elit a consequat. Aenean sed dui vitae sapien ornare lacinia. Donec nec rhoncus sem. Vivamus egestas lacinia orci eu elementum. Curabitur pharetra vulputate augue, sit amet gravida arcu posuere eu.</p>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis posuere risus nibh, quis lobortis lectus aliquet vitae. Nullam porttitor nisl sit amet est lacinia auctor. In eleifend quis ipsum sed suscipit. Vivamus mollis ornare ipsum fermentum luctus. Proin dapibus viverra libero in ultrices. Donec sed felis eleifend, varius neque accumsan, varius quam. Ut eleifend nisi quis velit aliquam, non porta nunc placerat. Sed sed quam lectus. Donec malesuada neque arcu, nec vestibulum magna pharetra nec. Cras sit amet viverra neque, vitae laoreet tellus. Sed ultrices ante eget arcu tincidunt tincidunt. Curabitur rutrum a elit a consequat. Aenean sed dui vitae sapien ornare lacinia. Donec nec rhoncus sem. Vivamus egestas lacinia orci eu elementum. Curabitur pharetra vulputate augue, sit amet gravida arcu posuere eu.</p>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis posuere risus nibh, quis lobortis lectus aliquet vitae. Nullam porttitor nisl sit amet est lacinia auctor. In eleifend quis ipsum sed suscipit. Vivamus mollis ornare ipsum fermentum luctus. Proin dapibus viverra libero in ultrices. Donec sed felis eleifend, varius neque accumsan, varius quam. Ut eleifend nisi quis velit aliquam, non porta nunc placerat. Sed sed quam lectus. Donec malesuada neque arcu, nec vestibulum magna pharetra nec. Cras sit amet viverra neque, vitae laoreet tellus. Sed ultrices ante eget arcu tincidunt tincidunt. Curabitur rutrum a elit a consequat. Aenean sed dui vitae sapien ornare lacinia. Donec nec rhoncus sem. Vivamus egestas lacinia orci eu elementum. Curabitur pharetra vulputate augue, sit amet gravida arcu posuere eu.</p>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis posuere risus nibh, quis lobortis lectus aliquet vitae. Nullam porttitor nisl sit amet est lacinia auctor. In eleifend quis ipsum sed suscipit. Vivamus mollis ornare ipsum fermentum luctus. Proin dapibus viverra libero in ultrices. Donec sed felis eleifend, varius neque accumsan, varius quam. Ut eleifend nisi quis velit aliquam, non porta nunc placerat. Sed sed quam lectus. Donec malesuada neque arcu, nec vestibulum magna pharetra nec. Cras sit amet viverra neque, vitae laoreet tellus. Sed ultrices ante eget arcu tincidunt tincidunt. Curabitur rutrum a elit a consequat. Aenean sed dui vitae sapien ornare lacinia. Donec nec rhoncus sem. Vivamus egestas lacinia orci eu elementum. Curabitur pharetra vulputate augue, sit amet gravida arcu posuere eu.</p>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis posuere risus nibh, quis lobortis lectus aliquet vitae. Nullam porttitor nisl sit amet est lacinia auctor. In eleifend quis ipsum sed suscipit. Vivamus mollis ornare ipsum fermentum luctus. Proin dapibus viverra libero in ultrices. Donec sed felis eleifend, varius neque accumsan, varius quam. Ut eleifend nisi quis velit aliquam, non porta nunc placerat. Sed sed quam lectus. Donec malesuada neque arcu, nec vestibulum magna pharetra nec. Cras sit amet viverra neque, vitae laoreet tellus. Sed ultrices ante eget arcu tincidunt tincidunt. Curabitur rutrum a elit a consequat. Aenean sed dui vitae sapien ornare lacinia. Donec nec rhoncus sem. Vivamus egestas lacinia orci eu elementum. Curabitur pharetra vulputate augue, sit amet gravida arcu posuere eu.</p>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis posuere risus nibh, quis lobortis lectus aliquet vitae. Nullam porttitor nisl sit amet est lacinia auctor. In eleifend quis ipsum sed suscipit. Vivamus mollis ornare ipsum fermentum luctus. Proin dapibus viverra libero in ultrices. Donec sed felis eleifend, varius neque accumsan, varius quam. Ut eleifend nisi quis velit aliquam, non porta nunc placerat. Sed sed quam lectus. Donec malesuada neque arcu, nec vestibulum magna pharetra nec. Cras sit amet viverra neque, vitae laoreet tellus. Sed ultrices ante eget arcu tincidunt tincidunt. Curabitur rutrum a elit a consequat. Aenean sed dui vitae sapien ornare lacinia. Donec nec rhoncus sem. Vivamus egestas lacinia orci eu elementum. Curabitur pharetra vulputate augue, sit amet gravida arcu posuere eu.</p>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis posuere risus nibh, quis lobortis lectus aliquet vitae. Nullam porttitor nisl sit amet est lacinia auctor. In eleifend quis ipsum sed suscipit. Vivamus mollis ornare ipsum fermentum luctus. Proin dapibus viverra libero in ultrices. Donec sed felis eleifend, varius neque accumsan, varius quam. Ut eleifend nisi quis velit aliquam, non porta nunc placerat. Sed sed quam lectus. Donec malesuada neque arcu, nec vestibulum magna pharetra nec. Cras sit amet viverra neque, vitae laoreet tellus. Sed ultrices ante eget arcu tincidunt tincidunt. Curabitur rutrum a elit a consequat. Aenean sed dui vitae sapien ornare lacinia. Donec nec rhoncus sem. Vivamus egestas lacinia orci eu elementum. Curabitur pharetra vulputate augue, sit amet gravida arcu posuere eu.</p>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis posuere risus nibh, quis lobortis lectus aliquet vitae. Nullam porttitor nisl sit amet est lacinia auctor. In eleifend quis ipsum sed suscipit. Vivamus mollis ornare ipsum fermentum luctus. Proin dapibus viverra libero in ultrices. Donec sed felis eleifend, varius neque accumsan, varius quam. Ut eleifend nisi quis velit aliquam, non porta nunc placerat. Sed sed quam lectus. Donec malesuada neque arcu, nec vestibulum magna pharetra nec. Cras sit amet viverra neque, vitae laoreet tellus. Sed ultrices ante eget arcu tincidunt tincidunt. Curabitur rutrum a elit a consequat. Aenean sed dui vitae sapien ornare lacinia. Donec nec rhoncus sem. Vivamus egestas lacinia orci eu elementum. Curabitur pharetra vulputate augue, sit amet gravida arcu posuere eu.</p>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis posuere risus nibh, quis lobortis lectus aliquet vitae. Nullam porttitor nisl sit amet est lacinia auctor. In eleifend quis ipsum sed suscipit. Vivamus mollis ornare ipsum fermentum luctus. Proin dapibus viverra libero in ultrices. Donec sed felis eleifend, varius neque accumsan, varius quam. Ut eleifend nisi quis velit aliquam, non porta nunc placerat. Sed sed quam lectus. Donec malesuada neque arcu, nec vestibulum magna pharetra nec. Cras sit amet viverra neque, vitae laoreet tellus. Sed ultrices ante eget arcu tincidunt tincidunt. Curabitur rutrum a elit a consequat. Aenean sed dui vitae sapien ornare lacinia. Donec nec rhoncus sem. Vivamus egestas lacinia orci eu elementum. Curabitur pharetra vulputate augue, sit amet gravida arcu posuere eu.</p>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis posuere risus nibh, quis lobortis lectus aliquet vitae. Nullam porttitor nisl sit amet est lacinia auctor. In eleifend quis ipsum sed suscipit. Vivamus mollis ornare ipsum fermentum luctus. Proin dapibus viverra libero in ultrices. Donec sed felis eleifend, varius neque accumsan, varius quam. Ut eleifend nisi quis velit aliquam, non porta nunc placerat. Sed sed quam lectus. Donec malesuada neque arcu, nec vestibulum magna pharetra nec. Cras sit amet viverra neque, vitae laoreet tellus. Sed ultrices ante eget arcu tincidunt tincidunt. Curabitur rutrum a elit a consequat. Aenean sed dui vitae sapien ornare lacinia. Donec nec rhoncus sem. Vivamus egestas lacinia orci eu elementum. Curabitur pharetra vulputate augue, sit amet gravida arcu posuere eu.</p>
                    </div>
                </div>
            </div>
    	</div>
    	<div class="insight" id="be-fearlessly-digital" data-insight="5">
    		<div class="marker">
    			<div><span>05</span></div>
    		</div>
            <div class="insightTitle">
                <h6>CIO Action Item #5</h6>
                <h3>Be fearlessly digital.</h3>
                <div class="social">
                    <a href="https://plus.google.com/share?url=http://accenture-hpit.herokuapp.com/index.php" target="_blank" class="google"></a>
                    <a href="http://www.facebook.com/share.php?u=http://accenture-hpit.herokuapp.com/index.php" target="_blank" class="facebook"></a>
                    <a href="http://twitter.com/share?url=http://accenture-hpit.herokuapp.com/index.php" target="_blank" class="twitter"></a>
                    <a href="http://www.linkedin.com/shareArticle?mini=true&url=http://accenture-hpit.herokuapp.com/index.php" target="_blank" class="linkedin"></a>
                </div>
            </div>
    		<div class="container content">
                <div class="row">
                    <!--div class="left-col">lorem ipsum...</div-->
                    <div class="right-col col-xs-12 col-sm-6 col-md-6 col-lg-6 col-sm-offset-6 col-md-offset-6 col-lg-offset-6">
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis posuere risus nibh, quis lobortis lectus aliquet vitae. Nullam porttitor nisl sit amet est lacinia auctor. In eleifend quis ipsum sed suscipit. Vivamus mollis ornare ipsum fermentum luctus. Proin dapibus viverra libero in ultrices. Donec sed felis eleifend, varius neque accumsan, varius quam. Ut eleifend nisi quis velit aliquam, non porta nunc placerat. Sed sed quam lectus. Donec malesuada neque arcu, nec vestibulum magna pharetra nec. Cras sit amet viverra neque, vitae laoreet tellus. Sed ultrices ante eget arcu tincidunt tincidunt. Curabitur rutrum a elit a consequat. Aenean sed dui vitae sapien ornare lacinia. Donec nec rhoncus sem. Vivamus egestas lacinia orci eu elementum. Curabitur pharetra vulputate augue, sit amet gravida arcu posuere eu.</p>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis posuere risus nibh, quis lobortis lectus aliquet vitae. Nullam porttitor nisl sit amet est lacinia auctor. In eleifend quis ipsum sed suscipit. Vivamus mollis ornare ipsum fermentum luctus. Proin dapibus viverra libero in ultrices. Donec sed felis eleifend, varius neque accumsan, varius quam. Ut eleifend nisi quis velit aliquam, non porta nunc placerat. Sed sed quam lectus. Donec malesuada neque arcu, nec vestibulum magna pharetra nec. Cras sit amet viverra neque, vitae laoreet tellus. Sed ultrices ante eget arcu tincidunt tincidunt. Curabitur rutrum a elit a consequat. Aenean sed dui vitae sapien ornare lacinia. Donec nec rhoncus sem. Vivamus egestas lacinia orci eu elementum. Curabitur pharetra vulputate augue, sit amet gravida arcu posuere eu.</p>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis posuere risus nibh, quis lobortis lectus aliquet vitae. Nullam porttitor nisl sit amet est lacinia auctor. In eleifend quis ipsum sed suscipit. Vivamus mollis ornare ipsum fermentum luctus. Proin dapibus viverra libero in ultrices. Donec sed felis eleifend, varius neque accumsan, varius quam. Ut eleifend nisi quis velit aliquam, non porta nunc placerat. Sed sed quam lectus. Donec malesuada neque arcu, nec vestibulum magna pharetra nec. Cras sit amet viverra neque, vitae laoreet tellus. Sed ultrices ante eget arcu tincidunt tincidunt. Curabitur rutrum a elit a consequat. Aenean sed dui vitae sapien ornare lacinia. Donec nec rhoncus sem. Vivamus egestas lacinia orci eu elementum. Curabitur pharetra vulputate augue, sit amet gravida arcu posuere eu.</p>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis posuere risus nibh, quis lobortis lectus aliquet vitae. Nullam porttitor nisl sit amet est lacinia auctor. In eleifend quis ipsum sed suscipit. Vivamus mollis ornare ipsum fermentum luctus. Proin dapibus viverra libero in ultrices. Donec sed felis eleifend, varius neque accumsan, varius quam. Ut eleifend nisi quis velit aliquam, non porta nunc placerat. Sed sed quam lectus. Donec malesuada neque arcu, nec vestibulum magna pharetra nec. Cras sit amet viverra neque, vitae laoreet tellus. Sed ultrices ante eget arcu tincidunt tincidunt. Curabitur rutrum a elit a consequat. Aenean sed dui vitae sapien ornare lacinia. Donec nec rhoncus sem. Vivamus egestas lacinia orci eu elementum. Curabitur pharetra vulputate augue, sit amet gravida arcu posuere eu.</p>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis posuere risus nibh, quis lobortis lectus aliquet vitae. Nullam porttitor nisl sit amet est lacinia auctor. In eleifend quis ipsum sed suscipit. Vivamus mollis ornare ipsum fermentum luctus. Proin dapibus viverra libero in ultrices. Donec sed felis eleifend, varius neque accumsan, varius quam. Ut eleifend nisi quis velit aliquam, non porta nunc placerat. Sed sed quam lectus. Donec malesuada neque arcu, nec vestibulum magna pharetra nec. Cras sit amet viverra neque, vitae laoreet tellus. Sed ultrices ante eget arcu tincidunt tincidunt. Curabitur rutrum a elit a consequat. Aenean sed dui vitae sapien ornare lacinia. Donec nec rhoncus sem. Vivamus egestas lacinia orci eu elementum. Curabitur pharetra vulputate augue, sit amet gravida arcu posuere eu.</p>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis posuere risus nibh, quis lobortis lectus aliquet vitae. Nullam porttitor nisl sit amet est lacinia auctor. In eleifend quis ipsum sed suscipit. Vivamus mollis ornare ipsum fermentum luctus. Proin dapibus viverra libero in ultrices. Donec sed felis eleifend, varius neque accumsan, varius quam. Ut eleifend nisi quis velit aliquam, non porta nunc placerat. Sed sed quam lectus. Donec malesuada neque arcu, nec vestibulum magna pharetra nec. Cras sit amet viverra neque, vitae laoreet tellus. Sed ultrices ante eget arcu tincidunt tincidunt. Curabitur rutrum a elit a consequat. Aenean sed dui vitae sapien ornare lacinia. Donec nec rhoncus sem. Vivamus egestas lacinia orci eu elementum. Curabitur pharetra vulputate augue, sit amet gravida arcu posuere eu.</p>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis posuere risus nibh, quis lobortis lectus aliquet vitae. Nullam porttitor nisl sit amet est lacinia auctor. In eleifend quis ipsum sed suscipit. Vivamus mollis ornare ipsum fermentum luctus. Proin dapibus viverra libero in ultrices. Donec sed felis eleifend, varius neque accumsan, varius quam. Ut eleifend nisi quis velit aliquam, non porta nunc placerat. Sed sed quam lectus. Donec malesuada neque arcu, nec vestibulum magna pharetra nec. Cras sit amet viverra neque, vitae laoreet tellus. Sed ultrices ante eget arcu tincidunt tincidunt. Curabitur rutrum a elit a consequat. Aenean sed dui vitae sapien ornare lacinia. Donec nec rhoncus sem. Vivamus egestas lacinia orci eu elementum. Curabitur pharetra vulputate augue, sit amet gravida arcu posuere eu.</p>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis posuere risus nibh, quis lobortis lectus aliquet vitae. Nullam porttitor nisl sit amet est lacinia auctor. In eleifend quis ipsum sed suscipit. Vivamus mollis ornare ipsum fermentum luctus. Proin dapibus viverra libero in ultrices. Donec sed felis eleifend, varius neque accumsan, varius quam. Ut eleifend nisi quis velit aliquam, non porta nunc placerat. Sed sed quam lectus. Donec malesuada neque arcu, nec vestibulum magna pharetra nec. Cras sit amet viverra neque, vitae laoreet tellus. Sed ultrices ante eget arcu tincidunt tincidunt. Curabitur rutrum a elit a consequat. Aenean sed dui vitae sapien ornare lacinia. Donec nec rhoncus sem. Vivamus egestas lacinia orci eu elementum. Curabitur pharetra vulputate augue, sit amet gravida arcu posuere eu.</p>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis posuere risus nibh, quis lobortis lectus aliquet vitae. Nullam porttitor nisl sit amet est lacinia auctor. In eleifend quis ipsum sed suscipit. Vivamus mollis ornare ipsum fermentum luctus. Proin dapibus viverra libero in ultrices. Donec sed felis eleifend, varius neque accumsan, varius quam. Ut eleifend nisi quis velit aliquam, non porta nunc placerat. Sed sed quam lectus. Donec malesuada neque arcu, nec vestibulum magna pharetra nec. Cras sit amet viverra neque, vitae laoreet tellus. Sed ultrices ante eget arcu tincidunt tincidunt. Curabitur rutrum a elit a consequat. Aenean sed dui vitae sapien ornare lacinia. Donec nec rhoncus sem. Vivamus egestas lacinia orci eu elementum. Curabitur pharetra vulputate augue, sit amet gravida arcu posuere eu.</p>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis posuere risus nibh, quis lobortis lectus aliquet vitae. Nullam porttitor nisl sit amet est lacinia auctor. In eleifend quis ipsum sed suscipit. Vivamus mollis ornare ipsum fermentum luctus. Proin dapibus viverra libero in ultrices. Donec sed felis eleifend, varius neque accumsan, varius quam. Ut eleifend nisi quis velit aliquam, non porta nunc placerat. Sed sed quam lectus. Donec malesuada neque arcu, nec vestibulum magna pharetra nec. Cras sit amet viverra neque, vitae laoreet tellus. Sed ultrices ante eget arcu tincidunt tincidunt. Curabitur rutrum a elit a consequat. Aenean sed dui vitae sapien ornare lacinia. Donec nec rhoncus sem. Vivamus egestas lacinia orci eu elementum. Curabitur pharetra vulputate augue, sit amet gravida arcu posuere eu.</p>
                    </div>
                </div>
            </div>
    	</div>
    	<div class="insight" id="survival-of-the-quickest" data-insight="6">
    		<div class="marker">
    			<div><span>06</span></div>
    		</div>
            <div class="insightTitle">
                <h6>CIO Action Item #6</h6>
                <h3>Survival of the quickest</h3>
                <div class="social">
                    <a href="https://plus.google.com/share?url=http://accenture-hpit.herokuapp.com/index.php" target="_blank" class="google"></a>
                    <a href="http://www.facebook.com/share.php?u=http://accenture-hpit.herokuapp.com/index.php" target="_blank" class="facebook"></a>
                    <a href="http://twitter.com/share?url=http://accenture-hpit.herokuapp.com/index.php" target="_blank" class="twitter"></a>
                    <a href="http://www.linkedin.com/shareArticle?mini=true&url=http://accenture-hpit.herokuapp.com/index.php" target="_blank" class="linkedin"></a>
                </div>
            </div>
    		<div class="container content">
                <div class="row">
                    <!--div class="left-col">lorem ipsum...</div-->
                    <div class="right-col col-xs-12 col-sm-6 col-md-6 col-lg-6 col-sm-offset-6 col-md-offset-6 col-lg-offset-6">
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis posuere risus nibh, quis lobortis lectus aliquet vitae. Nullam porttitor nisl sit amet est lacinia auctor. In eleifend quis ipsum sed suscipit. Vivamus mollis ornare ipsum fermentum luctus. Proin dapibus viverra libero in ultrices. Donec sed felis eleifend, varius neque accumsan, varius quam. Ut eleifend nisi quis velit aliquam, non porta nunc placerat. Sed sed quam lectus. Donec malesuada neque arcu, nec vestibulum magna pharetra nec. Cras sit amet viverra neque, vitae laoreet tellus. Sed ultrices ante eget arcu tincidunt tincidunt. Curabitur rutrum a elit a consequat. Aenean sed dui vitae sapien ornare lacinia. Donec nec rhoncus sem. Vivamus egestas lacinia orci eu elementum. Curabitur pharetra vulputate augue, sit amet gravida arcu posuere eu.</p>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis posuere risus nibh, quis lobortis lectus aliquet vitae. Nullam porttitor nisl sit amet est lacinia auctor. In eleifend quis ipsum sed suscipit. Vivamus mollis ornare ipsum fermentum luctus. Proin dapibus viverra libero in ultrices. Donec sed felis eleifend, varius neque accumsan, varius quam. Ut eleifend nisi quis velit aliquam, non porta nunc placerat. Sed sed quam lectus. Donec malesuada neque arcu, nec vestibulum magna pharetra nec. Cras sit amet viverra neque, vitae laoreet tellus. Sed ultrices ante eget arcu tincidunt tincidunt. Curabitur rutrum a elit a consequat. Aenean sed dui vitae sapien ornare lacinia. Donec nec rhoncus sem. Vivamus egestas lacinia orci eu elementum. Curabitur pharetra vulputate augue, sit amet gravida arcu posuere eu.</p>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis posuere risus nibh, quis lobortis lectus aliquet vitae. Nullam porttitor nisl sit amet est lacinia auctor. In eleifend quis ipsum sed suscipit. Vivamus mollis ornare ipsum fermentum luctus. Proin dapibus viverra libero in ultrices. Donec sed felis eleifend, varius neque accumsan, varius quam. Ut eleifend nisi quis velit aliquam, non porta nunc placerat. Sed sed quam lectus. Donec malesuada neque arcu, nec vestibulum magna pharetra nec. Cras sit amet viverra neque, vitae laoreet tellus. Sed ultrices ante eget arcu tincidunt tincidunt. Curabitur rutrum a elit a consequat. Aenean sed dui vitae sapien ornare lacinia. Donec nec rhoncus sem. Vivamus egestas lacinia orci eu elementum. Curabitur pharetra vulputate augue, sit amet gravida arcu posuere eu.</p>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis posuere risus nibh, quis lobortis lectus aliquet vitae. Nullam porttitor nisl sit amet est lacinia auctor. In eleifend quis ipsum sed suscipit. Vivamus mollis ornare ipsum fermentum luctus. Proin dapibus viverra libero in ultrices. Donec sed felis eleifend, varius neque accumsan, varius quam. Ut eleifend nisi quis velit aliquam, non porta nunc placerat. Sed sed quam lectus. Donec malesuada neque arcu, nec vestibulum magna pharetra nec. Cras sit amet viverra neque, vitae laoreet tellus. Sed ultrices ante eget arcu tincidunt tincidunt. Curabitur rutrum a elit a consequat. Aenean sed dui vitae sapien ornare lacinia. Donec nec rhoncus sem. Vivamus egestas lacinia orci eu elementum. Curabitur pharetra vulputate augue, sit amet gravida arcu posuere eu.</p>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis posuere risus nibh, quis lobortis lectus aliquet vitae. Nullam porttitor nisl sit amet est lacinia auctor. In eleifend quis ipsum sed suscipit. Vivamus mollis ornare ipsum fermentum luctus. Proin dapibus viverra libero in ultrices. Donec sed felis eleifend, varius neque accumsan, varius quam. Ut eleifend nisi quis velit aliquam, non porta nunc placerat. Sed sed quam lectus. Donec malesuada neque arcu, nec vestibulum magna pharetra nec. Cras sit amet viverra neque, vitae laoreet tellus. Sed ultrices ante eget arcu tincidunt tincidunt. Curabitur rutrum a elit a consequat. Aenean sed dui vitae sapien ornare lacinia. Donec nec rhoncus sem. Vivamus egestas lacinia orci eu elementum. Curabitur pharetra vulputate augue, sit amet gravida arcu posuere eu.</p>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis posuere risus nibh, quis lobortis lectus aliquet vitae. Nullam porttitor nisl sit amet est lacinia auctor. In eleifend quis ipsum sed suscipit. Vivamus mollis ornare ipsum fermentum luctus. Proin dapibus viverra libero in ultrices. Donec sed felis eleifend, varius neque accumsan, varius quam. Ut eleifend nisi quis velit aliquam, non porta nunc placerat. Sed sed quam lectus. Donec malesuada neque arcu, nec vestibulum magna pharetra nec. Cras sit amet viverra neque, vitae laoreet tellus. Sed ultrices ante eget arcu tincidunt tincidunt. Curabitur rutrum a elit a consequat. Aenean sed dui vitae sapien ornare lacinia. Donec nec rhoncus sem. Vivamus egestas lacinia orci eu elementum. Curabitur pharetra vulputate augue, sit amet gravida arcu posuere eu.</p>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis posuere risus nibh, quis lobortis lectus aliquet vitae. Nullam porttitor nisl sit amet est lacinia auctor. In eleifend quis ipsum sed suscipit. Vivamus mollis ornare ipsum fermentum luctus. Proin dapibus viverra libero in ultrices. Donec sed felis eleifend, varius neque accumsan, varius quam. Ut eleifend nisi quis velit aliquam, non porta nunc placerat. Sed sed quam lectus. Donec malesuada neque arcu, nec vestibulum magna pharetra nec. Cras sit amet viverra neque, vitae laoreet tellus. Sed ultrices ante eget arcu tincidunt tincidunt. Curabitur rutrum a elit a consequat. Aenean sed dui vitae sapien ornare lacinia. Donec nec rhoncus sem. Vivamus egestas lacinia orci eu elementum. Curabitur pharetra vulputate augue, sit amet gravida arcu posuere eu.</p>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis posuere risus nibh, quis lobortis lectus aliquet vitae. Nullam porttitor nisl sit amet est lacinia auctor. In eleifend quis ipsum sed suscipit. Vivamus mollis ornare ipsum fermentum luctus. Proin dapibus viverra libero in ultrices. Donec sed felis eleifend, varius neque accumsan, varius quam. Ut eleifend nisi quis velit aliquam, non porta nunc placerat. Sed sed quam lectus. Donec malesuada neque arcu, nec vestibulum magna pharetra nec. Cras sit amet viverra neque, vitae laoreet tellus. Sed ultrices ante eget arcu tincidunt tincidunt. Curabitur rutrum a elit a consequat. Aenean sed dui vitae sapien ornare lacinia. Donec nec rhoncus sem. Vivamus egestas lacinia orci eu elementum. Curabitur pharetra vulputate augue, sit amet gravida arcu posuere eu.</p>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis posuere risus nibh, quis lobortis lectus aliquet vitae. Nullam porttitor nisl sit amet est lacinia auctor. In eleifend quis ipsum sed suscipit. Vivamus mollis ornare ipsum fermentum luctus. Proin dapibus viverra libero in ultrices. Donec sed felis eleifend, varius neque accumsan, varius quam. Ut eleifend nisi quis velit aliquam, non porta nunc placerat. Sed sed quam lectus. Donec malesuada neque arcu, nec vestibulum magna pharetra nec. Cras sit amet viverra neque, vitae laoreet tellus. Sed ultrices ante eget arcu tincidunt tincidunt. Curabitur rutrum a elit a consequat. Aenean sed dui vitae sapien ornare lacinia. Donec nec rhoncus sem. Vivamus egestas lacinia orci eu elementum. Curabitur pharetra vulputate augue, sit amet gravida arcu posuere eu.</p>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis posuere risus nibh, quis lobortis lectus aliquet vitae. Nullam porttitor nisl sit amet est lacinia auctor. In eleifend quis ipsum sed suscipit. Vivamus mollis ornare ipsum fermentum luctus. Proin dapibus viverra libero in ultrices. Donec sed felis eleifend, varius neque accumsan, varius quam. Ut eleifend nisi quis velit aliquam, non porta nunc placerat. Sed sed quam lectus. Donec malesuada neque arcu, nec vestibulum magna pharetra nec. Cras sit amet viverra neque, vitae laoreet tellus. Sed ultrices ante eget arcu tincidunt tincidunt. Curabitur rutrum a elit a consequat. Aenean sed dui vitae sapien ornare lacinia. Donec nec rhoncus sem. Vivamus egestas lacinia orci eu elementum. Curabitur pharetra vulputate augue, sit amet gravida arcu posuere eu.</p>
                    </div>
                </div>
            </div>
    	</div>
    	<div class="insight" id="all-data-is-not-created-equal" data-insight="7">
    		<div class="marker">
    			<div><span>07</span></div>
    		</div>
            <div class="insightTitle">
                <h6>CIO Action Item #7</h6>
                <h3>All data is not created equal.</h3>
                <div class="social">
                    <a href="https://plus.google.com/share?url=http://accenture-hpit.herokuapp.com/index.php" target="_blank" class="google"></a>
                    <a href="http://www.facebook.com/share.php?u=http://accenture-hpit.herokuapp.com/index.php" target="_blank" class="facebook"></a>
                    <a href="http://twitter.com/share?url=http://accenture-hpit.herokuapp.com/index.php" target="_blank" class="twitter"></a>
                    <a href="http://www.linkedin.com/shareArticle?mini=true&url=http://accenture-hpit.herokuapp.com/index.php" target="_blank" class="linkedin"></a>
                </div>
            </div>
    		<div class="container content">
                <div class="row">
                    <!--div class="left-col">lorem ipsum...</div-->
                    <div class="right-col col-xs-12 col-sm-6 col-md-6 col-lg-6 col-sm-offset-6 col-md-offset-6 col-lg-offset-6">
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis posuere risus nibh, quis lobortis lectus aliquet vitae. Nullam porttitor nisl sit amet est lacinia auctor. In eleifend quis ipsum sed suscipit. Vivamus mollis ornare ipsum fermentum luctus. Proin dapibus viverra libero in ultrices. Donec sed felis eleifend, varius neque accumsan, varius quam. Ut eleifend nisi quis velit aliquam, non porta nunc placerat. Sed sed quam lectus. Donec malesuada neque arcu, nec vestibulum magna pharetra nec. Cras sit amet viverra neque, vitae laoreet tellus. Sed ultrices ante eget arcu tincidunt tincidunt. Curabitur rutrum a elit a consequat. Aenean sed dui vitae sapien ornare lacinia. Donec nec rhoncus sem. Vivamus egestas lacinia orci eu elementum. Curabitur pharetra vulputate augue, sit amet gravida arcu posuere eu.</p>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis posuere risus nibh, quis lobortis lectus aliquet vitae. Nullam porttitor nisl sit amet est lacinia auctor. In eleifend quis ipsum sed suscipit. Vivamus mollis ornare ipsum fermentum luctus. Proin dapibus viverra libero in ultrices. Donec sed felis eleifend, varius neque accumsan, varius quam. Ut eleifend nisi quis velit aliquam, non porta nunc placerat. Sed sed quam lectus. Donec malesuada neque arcu, nec vestibulum magna pharetra nec. Cras sit amet viverra neque, vitae laoreet tellus. Sed ultrices ante eget arcu tincidunt tincidunt. Curabitur rutrum a elit a consequat. Aenean sed dui vitae sapien ornare lacinia. Donec nec rhoncus sem. Vivamus egestas lacinia orci eu elementum. Curabitur pharetra vulputate augue, sit amet gravida arcu posuere eu.</p>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis posuere risus nibh, quis lobortis lectus aliquet vitae. Nullam porttitor nisl sit amet est lacinia auctor. In eleifend quis ipsum sed suscipit. Vivamus mollis ornare ipsum fermentum luctus. Proin dapibus viverra libero in ultrices. Donec sed felis eleifend, varius neque accumsan, varius quam. Ut eleifend nisi quis velit aliquam, non porta nunc placerat. Sed sed quam lectus. Donec malesuada neque arcu, nec vestibulum magna pharetra nec. Cras sit amet viverra neque, vitae laoreet tellus. Sed ultrices ante eget arcu tincidunt tincidunt. Curabitur rutrum a elit a consequat. Aenean sed dui vitae sapien ornare lacinia. Donec nec rhoncus sem. Vivamus egestas lacinia orci eu elementum. Curabitur pharetra vulputate augue, sit amet gravida arcu posuere eu.</p>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis posuere risus nibh, quis lobortis lectus aliquet vitae. Nullam porttitor nisl sit amet est lacinia auctor. In eleifend quis ipsum sed suscipit. Vivamus mollis ornare ipsum fermentum luctus. Proin dapibus viverra libero in ultrices. Donec sed felis eleifend, varius neque accumsan, varius quam. Ut eleifend nisi quis velit aliquam, non porta nunc placerat. Sed sed quam lectus. Donec malesuada neque arcu, nec vestibulum magna pharetra nec. Cras sit amet viverra neque, vitae laoreet tellus. Sed ultrices ante eget arcu tincidunt tincidunt. Curabitur rutrum a elit a consequat. Aenean sed dui vitae sapien ornare lacinia. Donec nec rhoncus sem. Vivamus egestas lacinia orci eu elementum. Curabitur pharetra vulputate augue, sit amet gravida arcu posuere eu.</p>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis posuere risus nibh, quis lobortis lectus aliquet vitae. Nullam porttitor nisl sit amet est lacinia auctor. In eleifend quis ipsum sed suscipit. Vivamus mollis ornare ipsum fermentum luctus. Proin dapibus viverra libero in ultrices. Donec sed felis eleifend, varius neque accumsan, varius quam. Ut eleifend nisi quis velit aliquam, non porta nunc placerat. Sed sed quam lectus. Donec malesuada neque arcu, nec vestibulum magna pharetra nec. Cras sit amet viverra neque, vitae laoreet tellus. Sed ultrices ante eget arcu tincidunt tincidunt. Curabitur rutrum a elit a consequat. Aenean sed dui vitae sapien ornare lacinia. Donec nec rhoncus sem. Vivamus egestas lacinia orci eu elementum. Curabitur pharetra vulputate augue, sit amet gravida arcu posuere eu.</p>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis posuere risus nibh, quis lobortis lectus aliquet vitae. Nullam porttitor nisl sit amet est lacinia auctor. In eleifend quis ipsum sed suscipit. Vivamus mollis ornare ipsum fermentum luctus. Proin dapibus viverra libero in ultrices. Donec sed felis eleifend, varius neque accumsan, varius quam. Ut eleifend nisi quis velit aliquam, non porta nunc placerat. Sed sed quam lectus. Donec malesuada neque arcu, nec vestibulum magna pharetra nec. Cras sit amet viverra neque, vitae laoreet tellus. Sed ultrices ante eget arcu tincidunt tincidunt. Curabitur rutrum a elit a consequat. Aenean sed dui vitae sapien ornare lacinia. Donec nec rhoncus sem. Vivamus egestas lacinia orci eu elementum. Curabitur pharetra vulputate augue, sit amet gravida arcu posuere eu.</p>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis posuere risus nibh, quis lobortis lectus aliquet vitae. Nullam porttitor nisl sit amet est lacinia auctor. In eleifend quis ipsum sed suscipit. Vivamus mollis ornare ipsum fermentum luctus. Proin dapibus viverra libero in ultrices. Donec sed felis eleifend, varius neque accumsan, varius quam. Ut eleifend nisi quis velit aliquam, non porta nunc placerat. Sed sed quam lectus. Donec malesuada neque arcu, nec vestibulum magna pharetra nec. Cras sit amet viverra neque, vitae laoreet tellus. Sed ultrices ante eget arcu tincidunt tincidunt. Curabitur rutrum a elit a consequat. Aenean sed dui vitae sapien ornare lacinia. Donec nec rhoncus sem. Vivamus egestas lacinia orci eu elementum. Curabitur pharetra vulputate augue, sit amet gravida arcu posuere eu.</p>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis posuere risus nibh, quis lobortis lectus aliquet vitae. Nullam porttitor nisl sit amet est lacinia auctor. In eleifend quis ipsum sed suscipit. Vivamus mollis ornare ipsum fermentum luctus. Proin dapibus viverra libero in ultrices. Donec sed felis eleifend, varius neque accumsan, varius quam. Ut eleifend nisi quis velit aliquam, non porta nunc placerat. Sed sed quam lectus. Donec malesuada neque arcu, nec vestibulum magna pharetra nec. Cras sit amet viverra neque, vitae laoreet tellus. Sed ultrices ante eget arcu tincidunt tincidunt. Curabitur rutrum a elit a consequat. Aenean sed dui vitae sapien ornare lacinia. Donec nec rhoncus sem. Vivamus egestas lacinia orci eu elementum. Curabitur pharetra vulputate augue, sit amet gravida arcu posuere eu.</p>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis posuere risus nibh, quis lobortis lectus aliquet vitae. Nullam porttitor nisl sit amet est lacinia auctor. In eleifend quis ipsum sed suscipit. Vivamus mollis ornare ipsum fermentum luctus. Proin dapibus viverra libero in ultrices. Donec sed felis eleifend, varius neque accumsan, varius quam. Ut eleifend nisi quis velit aliquam, non porta nunc placerat. Sed sed quam lectus. Donec malesuada neque arcu, nec vestibulum magna pharetra nec. Cras sit amet viverra neque, vitae laoreet tellus. Sed ultrices ante eget arcu tincidunt tincidunt. Curabitur rutrum a elit a consequat. Aenean sed dui vitae sapien ornare lacinia. Donec nec rhoncus sem. Vivamus egestas lacinia orci eu elementum. Curabitur pharetra vulputate augue, sit amet gravida arcu posuere eu.</p>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis posuere risus nibh, quis lobortis lectus aliquet vitae. Nullam porttitor nisl sit amet est lacinia auctor. In eleifend quis ipsum sed suscipit. Vivamus mollis ornare ipsum fermentum luctus. Proin dapibus viverra libero in ultrices. Donec sed felis eleifend, varius neque accumsan, varius quam. Ut eleifend nisi quis velit aliquam, non porta nunc placerat. Sed sed quam lectus. Donec malesuada neque arcu, nec vestibulum magna pharetra nec. Cras sit amet viverra neque, vitae laoreet tellus. Sed ultrices ante eget arcu tincidunt tincidunt. Curabitur rutrum a elit a consequat. Aenean sed dui vitae sapien ornare lacinia. Donec nec rhoncus sem. Vivamus egestas lacinia orci eu elementum. Curabitur pharetra vulputate augue, sit amet gravida arcu posuere eu.</p>
                    </div>
                </div>
            </div>
    	</div>
    	<div class="insight" id="power-to-the-people" data-insight="8">
    		<div class="marker">
    			<div><span>08</span></div>
    		</div>
            <div class="insightTitle">
                <h6>CIO Action Item #8</h6>
                <h3>Power to the people.</h3>
                <div class="social">
                    <a href="https://plus.google.com/share?url=http://accenture-hpit.herokuapp.com/index.php" target="_blank" class="google"></a>
                    <a href="http://www.facebook.com/share.php?u=http://accenture-hpit.herokuapp.com/index.php" target="_blank" class="facebook"></a>
                    <a href="http://twitter.com/share?url=http://accenture-hpit.herokuapp.com/index.php" target="_blank" class="twitter"></a>
                    <a href="http://www.linkedin.com/shareArticle?mini=true&url=http://accenture-hpit.herokuapp.com/index.php" target="_blank" class="linkedin"></a>
                </div>
            </div>
    		<div class="container content">
                <div class="row">
                    <!--div class="left-col">lorem ipsum...</div-->
                    <div class="right-col col-xs-12 col-sm-6 col-md-6 col-lg-6 col-sm-offset-6 col-md-offset-6 col-lg-offset-6">
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis posuere risus nibh, quis lobortis lectus aliquet vitae. Nullam porttitor nisl sit amet est lacinia auctor. In eleifend quis ipsum sed suscipit. Vivamus mollis ornare ipsum fermentum luctus. Proin dapibus viverra libero in ultrices. Donec sed felis eleifend, varius neque accumsan, varius quam. Ut eleifend nisi quis velit aliquam, non porta nunc placerat. Sed sed quam lectus. Donec malesuada neque arcu, nec vestibulum magna pharetra nec. Cras sit amet viverra neque, vitae laoreet tellus. Sed ultrices ante eget arcu tincidunt tincidunt. Curabitur rutrum a elit a consequat. Aenean sed dui vitae sapien ornare lacinia. Donec nec rhoncus sem. Vivamus egestas lacinia orci eu elementum. Curabitur pharetra vulputate augue, sit amet gravida arcu posuere eu.</p>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis posuere risus nibh, quis lobortis lectus aliquet vitae. Nullam porttitor nisl sit amet est lacinia auctor. In eleifend quis ipsum sed suscipit. Vivamus mollis ornare ipsum fermentum luctus. Proin dapibus viverra libero in ultrices. Donec sed felis eleifend, varius neque accumsan, varius quam. Ut eleifend nisi quis velit aliquam, non porta nunc placerat. Sed sed quam lectus. Donec malesuada neque arcu, nec vestibulum magna pharetra nec. Cras sit amet viverra neque, vitae laoreet tellus. Sed ultrices ante eget arcu tincidunt tincidunt. Curabitur rutrum a elit a consequat. Aenean sed dui vitae sapien ornare lacinia. Donec nec rhoncus sem. Vivamus egestas lacinia orci eu elementum. Curabitur pharetra vulputate augue, sit amet gravida arcu posuere eu.</p>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis posuere risus nibh, quis lobortis lectus aliquet vitae. Nullam porttitor nisl sit amet est lacinia auctor. In eleifend quis ipsum sed suscipit. Vivamus mollis ornare ipsum fermentum luctus. Proin dapibus viverra libero in ultrices. Donec sed felis eleifend, varius neque accumsan, varius quam. Ut eleifend nisi quis velit aliquam, non porta nunc placerat. Sed sed quam lectus. Donec malesuada neque arcu, nec vestibulum magna pharetra nec. Cras sit amet viverra neque, vitae laoreet tellus. Sed ultrices ante eget arcu tincidunt tincidunt. Curabitur rutrum a elit a consequat. Aenean sed dui vitae sapien ornare lacinia. Donec nec rhoncus sem. Vivamus egestas lacinia orci eu elementum. Curabitur pharetra vulputate augue, sit amet gravida arcu posuere eu.</p>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis posuere risus nibh, quis lobortis lectus aliquet vitae. Nullam porttitor nisl sit amet est lacinia auctor. In eleifend quis ipsum sed suscipit. Vivamus mollis ornare ipsum fermentum luctus. Proin dapibus viverra libero in ultrices. Donec sed felis eleifend, varius neque accumsan, varius quam. Ut eleifend nisi quis velit aliquam, non porta nunc placerat. Sed sed quam lectus. Donec malesuada neque arcu, nec vestibulum magna pharetra nec. Cras sit amet viverra neque, vitae laoreet tellus. Sed ultrices ante eget arcu tincidunt tincidunt. Curabitur rutrum a elit a consequat. Aenean sed dui vitae sapien ornare lacinia. Donec nec rhoncus sem. Vivamus egestas lacinia orci eu elementum. Curabitur pharetra vulputate augue, sit amet gravida arcu posuere eu.</p>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis posuere risus nibh, quis lobortis lectus aliquet vitae. Nullam porttitor nisl sit amet est lacinia auctor. In eleifend quis ipsum sed suscipit. Vivamus mollis ornare ipsum fermentum luctus. Proin dapibus viverra libero in ultrices. Donec sed felis eleifend, varius neque accumsan, varius quam. Ut eleifend nisi quis velit aliquam, non porta nunc placerat. Sed sed quam lectus. Donec malesuada neque arcu, nec vestibulum magna pharetra nec. Cras sit amet viverra neque, vitae laoreet tellus. Sed ultrices ante eget arcu tincidunt tincidunt. Curabitur rutrum a elit a consequat. Aenean sed dui vitae sapien ornare lacinia. Donec nec rhoncus sem. Vivamus egestas lacinia orci eu elementum. Curabitur pharetra vulputate augue, sit amet gravida arcu posuere eu.</p>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis posuere risus nibh, quis lobortis lectus aliquet vitae. Nullam porttitor nisl sit amet est lacinia auctor. In eleifend quis ipsum sed suscipit. Vivamus mollis ornare ipsum fermentum luctus. Proin dapibus viverra libero in ultrices. Donec sed felis eleifend, varius neque accumsan, varius quam. Ut eleifend nisi quis velit aliquam, non porta nunc placerat. Sed sed quam lectus. Donec malesuada neque arcu, nec vestibulum magna pharetra nec. Cras sit amet viverra neque, vitae laoreet tellus. Sed ultrices ante eget arcu tincidunt tincidunt. Curabitur rutrum a elit a consequat. Aenean sed dui vitae sapien ornare lacinia. Donec nec rhoncus sem. Vivamus egestas lacinia orci eu elementum. Curabitur pharetra vulputate augue, sit amet gravida arcu posuere eu.</p>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis posuere risus nibh, quis lobortis lectus aliquet vitae. Nullam porttitor nisl sit amet est lacinia auctor. In eleifend quis ipsum sed suscipit. Vivamus mollis ornare ipsum fermentum luctus. Proin dapibus viverra libero in ultrices. Donec sed felis eleifend, varius neque accumsan, varius quam. Ut eleifend nisi quis velit aliquam, non porta nunc placerat. Sed sed quam lectus. Donec malesuada neque arcu, nec vestibulum magna pharetra nec. Cras sit amet viverra neque, vitae laoreet tellus. Sed ultrices ante eget arcu tincidunt tincidunt. Curabitur rutrum a elit a consequat. Aenean sed dui vitae sapien ornare lacinia. Donec nec rhoncus sem. Vivamus egestas lacinia orci eu elementum. Curabitur pharetra vulputate augue, sit amet gravida arcu posuere eu.</p>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis posuere risus nibh, quis lobortis lectus aliquet vitae. Nullam porttitor nisl sit amet est lacinia auctor. In eleifend quis ipsum sed suscipit. Vivamus mollis ornare ipsum fermentum luctus. Proin dapibus viverra libero in ultrices. Donec sed felis eleifend, varius neque accumsan, varius quam. Ut eleifend nisi quis velit aliquam, non porta nunc placerat. Sed sed quam lectus. Donec malesuada neque arcu, nec vestibulum magna pharetra nec. Cras sit amet viverra neque, vitae laoreet tellus. Sed ultrices ante eget arcu tincidunt tincidunt. Curabitur rutrum a elit a consequat. Aenean sed dui vitae sapien ornare lacinia. Donec nec rhoncus sem. Vivamus egestas lacinia orci eu elementum. Curabitur pharetra vulputate augue, sit amet gravida arcu posuere eu.</p>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis posuere risus nibh, quis lobortis lectus aliquet vitae. Nullam porttitor nisl sit amet est lacinia auctor. In eleifend quis ipsum sed suscipit. Vivamus mollis ornare ipsum fermentum luctus. Proin dapibus viverra libero in ultrices. Donec sed felis eleifend, varius neque accumsan, varius quam. Ut eleifend nisi quis velit aliquam, non porta nunc placerat. Sed sed quam lectus. Donec malesuada neque arcu, nec vestibulum magna pharetra nec. Cras sit amet viverra neque, vitae laoreet tellus. Sed ultrices ante eget arcu tincidunt tincidunt. Curabitur rutrum a elit a consequat. Aenean sed dui vitae sapien ornare lacinia. Donec nec rhoncus sem. Vivamus egestas lacinia orci eu elementum. Curabitur pharetra vulputate augue, sit amet gravida arcu posuere eu.</p>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis posuere risus nibh, quis lobortis lectus aliquet vitae. Nullam porttitor nisl sit amet est lacinia auctor. In eleifend quis ipsum sed suscipit. Vivamus mollis ornare ipsum fermentum luctus. Proin dapibus viverra libero in ultrices. Donec sed felis eleifend, varius neque accumsan, varius quam. Ut eleifend nisi quis velit aliquam, non porta nunc placerat. Sed sed quam lectus. Donec malesuada neque arcu, nec vestibulum magna pharetra nec. Cras sit amet viverra neque, vitae laoreet tellus. Sed ultrices ante eget arcu tincidunt tincidunt. Curabitur rutrum a elit a consequat. Aenean sed dui vitae sapien ornare lacinia. Donec nec rhoncus sem. Vivamus egestas lacinia orci eu elementum. Curabitur pharetra vulputate augue, sit amet gravida arcu posuere eu.</p>
                    </div>
                </div>
            </div>
    	</div>
    	<div class="insight" id="build-your-capabilities-around-talent-not-technology" data-insight="9">
    		<div class="marker">
    			<div><span>09</span></div>
    		</div>
            <div class="insightTitle">
                <h6>CIO Action Item #9</h6>
                <h3>Build your capabilities around talent, not technology.</h3>
                <div class="social">
                    <a href="https://plus.google.com/share?url=http://accenture-hpit.herokuapp.com/index.php" target="_blank" class="google"></a>
                    <a href="http://www.facebook.com/share.php?u=http://accenture-hpit.herokuapp.com/index.php" target="_blank" class="facebook"></a>
                    <a href="http://twitter.com/share?url=http://accenture-hpit.herokuapp.com/index.php" target="_blank" class="twitter"></a>
                    <a href="http://www.linkedin.com/shareArticle?mini=true&url=http://accenture-hpit.herokuapp.com/index.php" target="_blank" class="linkedin"></a>
                </div>
            </div>
    		<div class="container content">
                <div class="row">
                    <!--div class="left-col">lorem ipsum...</div-->
                    <div class="right-col col-xs-12 col-sm-6 col-md-6 col-lg-6 col-sm-offset-6 col-md-offset-6 col-lg-offset-6">
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis posuere risus nibh, quis lobortis lectus aliquet vitae. Nullam porttitor nisl sit amet est lacinia auctor. In eleifend quis ipsum sed suscipit. Vivamus mollis ornare ipsum fermentum luctus. Proin dapibus viverra libero in ultrices. Donec sed felis eleifend, varius neque accumsan, varius quam. Ut eleifend nisi quis velit aliquam, non porta nunc placerat. Sed sed quam lectus. Donec malesuada neque arcu, nec vestibulum magna pharetra nec. Cras sit amet viverra neque, vitae laoreet tellus. Sed ultrices ante eget arcu tincidunt tincidunt. Curabitur rutrum a elit a consequat. Aenean sed dui vitae sapien ornare lacinia. Donec nec rhoncus sem. Vivamus egestas lacinia orci eu elementum. Curabitur pharetra vulputate augue, sit amet gravida arcu posuere eu.</p>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis posuere risus nibh, quis lobortis lectus aliquet vitae. Nullam porttitor nisl sit amet est lacinia auctor. In eleifend quis ipsum sed suscipit. Vivamus mollis ornare ipsum fermentum luctus. Proin dapibus viverra libero in ultrices. Donec sed felis eleifend, varius neque accumsan, varius quam. Ut eleifend nisi quis velit aliquam, non porta nunc placerat. Sed sed quam lectus. Donec malesuada neque arcu, nec vestibulum magna pharetra nec. Cras sit amet viverra neque, vitae laoreet tellus. Sed ultrices ante eget arcu tincidunt tincidunt. Curabitur rutrum a elit a consequat. Aenean sed dui vitae sapien ornare lacinia. Donec nec rhoncus sem. Vivamus egestas lacinia orci eu elementum. Curabitur pharetra vulputate augue, sit amet gravida arcu posuere eu.</p>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis posuere risus nibh, quis lobortis lectus aliquet vitae. Nullam porttitor nisl sit amet est lacinia auctor. In eleifend quis ipsum sed suscipit. Vivamus mollis ornare ipsum fermentum luctus. Proin dapibus viverra libero in ultrices. Donec sed felis eleifend, varius neque accumsan, varius quam. Ut eleifend nisi quis velit aliquam, non porta nunc placerat. Sed sed quam lectus. Donec malesuada neque arcu, nec vestibulum magna pharetra nec. Cras sit amet viverra neque, vitae laoreet tellus. Sed ultrices ante eget arcu tincidunt tincidunt. Curabitur rutrum a elit a consequat. Aenean sed dui vitae sapien ornare lacinia. Donec nec rhoncus sem. Vivamus egestas lacinia orci eu elementum. Curabitur pharetra vulputate augue, sit amet gravida arcu posuere eu.</p>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis posuere risus nibh, quis lobortis lectus aliquet vitae. Nullam porttitor nisl sit amet est lacinia auctor. In eleifend quis ipsum sed suscipit. Vivamus mollis ornare ipsum fermentum luctus. Proin dapibus viverra libero in ultrices. Donec sed felis eleifend, varius neque accumsan, varius quam. Ut eleifend nisi quis velit aliquam, non porta nunc placerat. Sed sed quam lectus. Donec malesuada neque arcu, nec vestibulum magna pharetra nec. Cras sit amet viverra neque, vitae laoreet tellus. Sed ultrices ante eget arcu tincidunt tincidunt. Curabitur rutrum a elit a consequat. Aenean sed dui vitae sapien ornare lacinia. Donec nec rhoncus sem. Vivamus egestas lacinia orci eu elementum. Curabitur pharetra vulputate augue, sit amet gravida arcu posuere eu.</p>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis posuere risus nibh, quis lobortis lectus aliquet vitae. Nullam porttitor nisl sit amet est lacinia auctor. In eleifend quis ipsum sed suscipit. Vivamus mollis ornare ipsum fermentum luctus. Proin dapibus viverra libero in ultrices. Donec sed felis eleifend, varius neque accumsan, varius quam. Ut eleifend nisi quis velit aliquam, non porta nunc placerat. Sed sed quam lectus. Donec malesuada neque arcu, nec vestibulum magna pharetra nec. Cras sit amet viverra neque, vitae laoreet tellus. Sed ultrices ante eget arcu tincidunt tincidunt. Curabitur rutrum a elit a consequat. Aenean sed dui vitae sapien ornare lacinia. Donec nec rhoncus sem. Vivamus egestas lacinia orci eu elementum. Curabitur pharetra vulputate augue, sit amet gravida arcu posuere eu.</p>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis posuere risus nibh, quis lobortis lectus aliquet vitae. Nullam porttitor nisl sit amet est lacinia auctor. In eleifend quis ipsum sed suscipit. Vivamus mollis ornare ipsum fermentum luctus. Proin dapibus viverra libero in ultrices. Donec sed felis eleifend, varius neque accumsan, varius quam. Ut eleifend nisi quis velit aliquam, non porta nunc placerat. Sed sed quam lectus. Donec malesuada neque arcu, nec vestibulum magna pharetra nec. Cras sit amet viverra neque, vitae laoreet tellus. Sed ultrices ante eget arcu tincidunt tincidunt. Curabitur rutrum a elit a consequat. Aenean sed dui vitae sapien ornare lacinia. Donec nec rhoncus sem. Vivamus egestas lacinia orci eu elementum. Curabitur pharetra vulputate augue, sit amet gravida arcu posuere eu.</p>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis posuere risus nibh, quis lobortis lectus aliquet vitae. Nullam porttitor nisl sit amet est lacinia auctor. In eleifend quis ipsum sed suscipit. Vivamus mollis ornare ipsum fermentum luctus. Proin dapibus viverra libero in ultrices. Donec sed felis eleifend, varius neque accumsan, varius quam. Ut eleifend nisi quis velit aliquam, non porta nunc placerat. Sed sed quam lectus. Donec malesuada neque arcu, nec vestibulum magna pharetra nec. Cras sit amet viverra neque, vitae laoreet tellus. Sed ultrices ante eget arcu tincidunt tincidunt. Curabitur rutrum a elit a consequat. Aenean sed dui vitae sapien ornare lacinia. Donec nec rhoncus sem. Vivamus egestas lacinia orci eu elementum. Curabitur pharetra vulputate augue, sit amet gravida arcu posuere eu.</p>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis posuere risus nibh, quis lobortis lectus aliquet vitae. Nullam porttitor nisl sit amet est lacinia auctor. In eleifend quis ipsum sed suscipit. Vivamus mollis ornare ipsum fermentum luctus. Proin dapibus viverra libero in ultrices. Donec sed felis eleifend, varius neque accumsan, varius quam. Ut eleifend nisi quis velit aliquam, non porta nunc placerat. Sed sed quam lectus. Donec malesuada neque arcu, nec vestibulum magna pharetra nec. Cras sit amet viverra neque, vitae laoreet tellus. Sed ultrices ante eget arcu tincidunt tincidunt. Curabitur rutrum a elit a consequat. Aenean sed dui vitae sapien ornare lacinia. Donec nec rhoncus sem. Vivamus egestas lacinia orci eu elementum. Curabitur pharetra vulputate augue, sit amet gravida arcu posuere eu.</p>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis posuere risus nibh, quis lobortis lectus aliquet vitae. Nullam porttitor nisl sit amet est lacinia auctor. In eleifend quis ipsum sed suscipit. Vivamus mollis ornare ipsum fermentum luctus. Proin dapibus viverra libero in ultrices. Donec sed felis eleifend, varius neque accumsan, varius quam. Ut eleifend nisi quis velit aliquam, non porta nunc placerat. Sed sed quam lectus. Donec malesuada neque arcu, nec vestibulum magna pharetra nec. Cras sit amet viverra neque, vitae laoreet tellus. Sed ultrices ante eget arcu tincidunt tincidunt. Curabitur rutrum a elit a consequat. Aenean sed dui vitae sapien ornare lacinia. Donec nec rhoncus sem. Vivamus egestas lacinia orci eu elementum. Curabitur pharetra vulputate augue, sit amet gravida arcu posuere eu.</p>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis posuere risus nibh, quis lobortis lectus aliquet vitae. Nullam porttitor nisl sit amet est lacinia auctor. In eleifend quis ipsum sed suscipit. Vivamus mollis ornare ipsum fermentum luctus. Proin dapibus viverra libero in ultrices. Donec sed felis eleifend, varius neque accumsan, varius quam. Ut eleifend nisi quis velit aliquam, non porta nunc placerat. Sed sed quam lectus. Donec malesuada neque arcu, nec vestibulum magna pharetra nec. Cras sit amet viverra neque, vitae laoreet tellus. Sed ultrices ante eget arcu tincidunt tincidunt. Curabitur rutrum a elit a consequat. Aenean sed dui vitae sapien ornare lacinia. Donec nec rhoncus sem. Vivamus egestas lacinia orci eu elementum. Curabitur pharetra vulputate augue, sit amet gravida arcu posuere eu.</p>
                    </div>
                </div>
            </div>
    	</div>
    	<div class="insight" id="take-a-holistic-stance-on-security-and-risk" data-insight="10">
    		<div class="marker">
    			<div><span>10</span></div>
    		</div>
            <div class="insightTitle">
                <h6>CIO Action Item #10</h6>
                <h3>Take a holistic stance on security and risk</h3>
                <div class="social">
                    <a href="https://plus.google.com/share?url=http://accenture-hpit.herokuapp.com/index.php" target="_blank" class="google"></a>
                    <a href="http://www.facebook.com/share.php?u=http://accenture-hpit.herokuapp.com/index.php" target="_blank" class="facebook"></a>
                    <a href="http://twitter.com/share?url=http://accenture-hpit.herokuapp.com/index.php" target="_blank" class="twitter"></a>
                    <a href="http://www.linkedin.com/shareArticle?mini=true&url=http://accenture-hpit.herokuapp.com/index.php" target="_blank" class="linkedin"></a>
                </div>
            </div>
    		<div class="container content">
                <div class="row">
                    <!--div class="left-col">lorem ipsum...</div-->
                    <div class="right-col col-xs-12 col-sm-6 col-md-6 col-lg-6 col-sm-offset-6 col-md-offset-6 col-lg-offset-6">
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis posuere risus nibh, quis lobortis lectus aliquet vitae. Nullam porttitor nisl sit amet est lacinia auctor. In eleifend quis ipsum sed suscipit. Vivamus mollis ornare ipsum fermentum luctus. Proin dapibus viverra libero in ultrices. Donec sed felis eleifend, varius neque accumsan, varius quam. Ut eleifend nisi quis velit aliquam, non porta nunc placerat. Sed sed quam lectus. Donec malesuada neque arcu, nec vestibulum magna pharetra nec. Cras sit amet viverra neque, vitae laoreet tellus. Sed ultrices ante eget arcu tincidunt tincidunt. Curabitur rutrum a elit a consequat. Aenean sed dui vitae sapien ornare lacinia. Donec nec rhoncus sem. Vivamus egestas lacinia orci eu elementum. Curabitur pharetra vulputate augue, sit amet gravida arcu posuere eu.</p>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis posuere risus nibh, quis lobortis lectus aliquet vitae. Nullam porttitor nisl sit amet est lacinia auctor. In eleifend quis ipsum sed suscipit. Vivamus mollis ornare ipsum fermentum luctus. Proin dapibus viverra libero in ultrices. Donec sed felis eleifend, varius neque accumsan, varius quam. Ut eleifend nisi quis velit aliquam, non porta nunc placerat. Sed sed quam lectus. Donec malesuada neque arcu, nec vestibulum magna pharetra nec. Cras sit amet viverra neque, vitae laoreet tellus. Sed ultrices ante eget arcu tincidunt tincidunt. Curabitur rutrum a elit a consequat. Aenean sed dui vitae sapien ornare lacinia. Donec nec rhoncus sem. Vivamus egestas lacinia orci eu elementum. Curabitur pharetra vulputate augue, sit amet gravida arcu posuere eu.</p>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis posuere risus nibh, quis lobortis lectus aliquet vitae. Nullam porttitor nisl sit amet est lacinia auctor. In eleifend quis ipsum sed suscipit. Vivamus mollis ornare ipsum fermentum luctus. Proin dapibus viverra libero in ultrices. Donec sed felis eleifend, varius neque accumsan, varius quam. Ut eleifend nisi quis velit aliquam, non porta nunc placerat. Sed sed quam lectus. Donec malesuada neque arcu, nec vestibulum magna pharetra nec. Cras sit amet viverra neque, vitae laoreet tellus. Sed ultrices ante eget arcu tincidunt tincidunt. Curabitur rutrum a elit a consequat. Aenean sed dui vitae sapien ornare lacinia. Donec nec rhoncus sem. Vivamus egestas lacinia orci eu elementum. Curabitur pharetra vulputate augue, sit amet gravida arcu posuere eu.</p>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis posuere risus nibh, quis lobortis lectus aliquet vitae. Nullam porttitor nisl sit amet est lacinia auctor. In eleifend quis ipsum sed suscipit. Vivamus mollis ornare ipsum fermentum luctus. Proin dapibus viverra libero in ultrices. Donec sed felis eleifend, varius neque accumsan, varius quam. Ut eleifend nisi quis velit aliquam, non porta nunc placerat. Sed sed quam lectus. Donec malesuada neque arcu, nec vestibulum magna pharetra nec. Cras sit amet viverra neque, vitae laoreet tellus. Sed ultrices ante eget arcu tincidunt tincidunt. Curabitur rutrum a elit a consequat. Aenean sed dui vitae sapien ornare lacinia. Donec nec rhoncus sem. Vivamus egestas lacinia orci eu elementum. Curabitur pharetra vulputate augue, sit amet gravida arcu posuere eu.</p>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis posuere risus nibh, quis lobortis lectus aliquet vitae. Nullam porttitor nisl sit amet est lacinia auctor. In eleifend quis ipsum sed suscipit. Vivamus mollis ornare ipsum fermentum luctus. Proin dapibus viverra libero in ultrices. Donec sed felis eleifend, varius neque accumsan, varius quam. Ut eleifend nisi quis velit aliquam, non porta nunc placerat. Sed sed quam lectus. Donec malesuada neque arcu, nec vestibulum magna pharetra nec. Cras sit amet viverra neque, vitae laoreet tellus. Sed ultrices ante eget arcu tincidunt tincidunt. Curabitur rutrum a elit a consequat. Aenean sed dui vitae sapien ornare lacinia. Donec nec rhoncus sem. Vivamus egestas lacinia orci eu elementum. Curabitur pharetra vulputate augue, sit amet gravida arcu posuere eu.</p>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis posuere risus nibh, quis lobortis lectus aliquet vitae. Nullam porttitor nisl sit amet est lacinia auctor. In eleifend quis ipsum sed suscipit. Vivamus mollis ornare ipsum fermentum luctus. Proin dapibus viverra libero in ultrices. Donec sed felis eleifend, varius neque accumsan, varius quam. Ut eleifend nisi quis velit aliquam, non porta nunc placerat. Sed sed quam lectus. Donec malesuada neque arcu, nec vestibulum magna pharetra nec. Cras sit amet viverra neque, vitae laoreet tellus. Sed ultrices ante eget arcu tincidunt tincidunt. Curabitur rutrum a elit a consequat. Aenean sed dui vitae sapien ornare lacinia. Donec nec rhoncus sem. Vivamus egestas lacinia orci eu elementum. Curabitur pharetra vulputate augue, sit amet gravida arcu posuere eu.</p>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis posuere risus nibh, quis lobortis lectus aliquet vitae. Nullam porttitor nisl sit amet est lacinia auctor. In eleifend quis ipsum sed suscipit. Vivamus mollis ornare ipsum fermentum luctus. Proin dapibus viverra libero in ultrices. Donec sed felis eleifend, varius neque accumsan, varius quam. Ut eleifend nisi quis velit aliquam, non porta nunc placerat. Sed sed quam lectus. Donec malesuada neque arcu, nec vestibulum magna pharetra nec. Cras sit amet viverra neque, vitae laoreet tellus. Sed ultrices ante eget arcu tincidunt tincidunt. Curabitur rutrum a elit a consequat. Aenean sed dui vitae sapien ornare lacinia. Donec nec rhoncus sem. Vivamus egestas lacinia orci eu elementum. Curabitur pharetra vulputate augue, sit amet gravida arcu posuere eu.</p>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis posuere risus nibh, quis lobortis lectus aliquet vitae. Nullam porttitor nisl sit amet est lacinia auctor. In eleifend quis ipsum sed suscipit. Vivamus mollis ornare ipsum fermentum luctus. Proin dapibus viverra libero in ultrices. Donec sed felis eleifend, varius neque accumsan, varius quam. Ut eleifend nisi quis velit aliquam, non porta nunc placerat. Sed sed quam lectus. Donec malesuada neque arcu, nec vestibulum magna pharetra nec. Cras sit amet viverra neque, vitae laoreet tellus. Sed ultrices ante eget arcu tincidunt tincidunt. Curabitur rutrum a elit a consequat. Aenean sed dui vitae sapien ornare lacinia. Donec nec rhoncus sem. Vivamus egestas lacinia orci eu elementum. Curabitur pharetra vulputate augue, sit amet gravida arcu posuere eu.</p>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis posuere risus nibh, quis lobortis lectus aliquet vitae. Nullam porttitor nisl sit amet est lacinia auctor. In eleifend quis ipsum sed suscipit. Vivamus mollis ornare ipsum fermentum luctus. Proin dapibus viverra libero in ultrices. Donec sed felis eleifend, varius neque accumsan, varius quam. Ut eleifend nisi quis velit aliquam, non porta nunc placerat. Sed sed quam lectus. Donec malesuada neque arcu, nec vestibulum magna pharetra nec. Cras sit amet viverra neque, vitae laoreet tellus. Sed ultrices ante eget arcu tincidunt tincidunt. Curabitur rutrum a elit a consequat. Aenean sed dui vitae sapien ornare lacinia. Donec nec rhoncus sem. Vivamus egestas lacinia orci eu elementum. Curabitur pharetra vulputate augue, sit amet gravida arcu posuere eu.</p>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis posuere risus nibh, quis lobortis lectus aliquet vitae. Nullam porttitor nisl sit amet est lacinia auctor. In eleifend quis ipsum sed suscipit. Vivamus mollis ornare ipsum fermentum luctus. Proin dapibus viverra libero in ultrices. Donec sed felis eleifend, varius neque accumsan, varius quam. Ut eleifend nisi quis velit aliquam, non porta nunc placerat. Sed sed quam lectus. Donec malesuada neque arcu, nec vestibulum magna pharetra nec. Cras sit amet viverra neque, vitae laoreet tellus. Sed ultrices ante eget arcu tincidunt tincidunt. Curabitur rutrum a elit a consequat. Aenean sed dui vitae sapien ornare lacinia. Donec nec rhoncus sem. Vivamus egestas lacinia orci eu elementum. Curabitur pharetra vulputate augue, sit amet gravida arcu posuere eu.</p>
                    </div>
                </div>
            </div>
    	</div>
    	<div id="footer">footer...<div>
    	<div>
    </div>

		<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
		<script src="http://code.jquery.com/jquery.js"></script>
		<!-- Include all compiled plugins (below), or include individual files as needed -->
        <script src="http://assets.delvenetworks.com/player/embed.js"></script>
		<script src="js/bootstrap.min.js"></script>
		<script src="js/jquery.easing.1.3.js"></script>
		<script src="js/jquery.scrollTo-1.4.3.1-min.js"></script>
		<script src="js/jquery.localscroll-1.2.7-min.js"></script>
		<script src="js/hpit.js"></script>
	</body>
</html>